platform :ios, '13.0'

target 'SchoolRating' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'R.swift', '5.0.3'

  # Pods for SchoolRating

  target 'SchoolRatingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.7.2'
  end

  target 'SchoolRatingUITests' do
    # Pods for testing
  end

end
